CREATE TABLE IF NOT EXISTS user_points (
    id SERIAL PRIMARY KEY,
    address VARCHAR(42) NOT NULL,
    points INTEGER NOT NULL,
    event VARCHAR(10) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);